In [1]:
# importing libraries
import pandas as pd
import numpy as np

In [2]:
# display all column
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

In [3]:
# loading datasets
users = pd.read_csv("C:/Users/deepd/Desktop/Banking Fraud Detection Analytics/Dataset/Raw_Data/users.csv")
cards = pd.read_csv("C:/Users/deepd/Desktop/Banking Fraud Detection Analytics/Dataset/Raw_Data/cards.csv")
transactions = pd.read_csv("C:/Users/deepd/Desktop/Banking Fraud Detection Analytics/Dataset/Raw_Data/credit_card_transactions.csv")

In [4]:
# checking dataset load or not
print(users.shape)
print(cards.shape)
print(transactions.shape)

(2000, 18)
(6146, 13)
(24386900, 15)

In [5]:
# viewing first 5 rows
users.head()

,Person,Current Age,Retirement Age,Birth Year,Birth Month,Gender,Address,Apartment,City,State,Zipcode,Latitude,Longitude,Per Capita Income - Zipcode,Yearly Income - Person,Total Debt,FICO Score,Num Credit Cards
0,Hazel Robinson,53,66,1966,11,Female,462 Rose Lane,NaN,La Verne,CA,91750,34.15,-117.76,$29278,$59696,$127613,787,5
1,Sasha Sadr,53,68,1966,12,Female,3606 Federal Boulevard,NaN,Little Neck,NY,11363,40.76,-73.74,$37891,$77254,$191349,701,5
2,Saanvi Lee,81,67,1938,11,Female,766 Third Drive,NaN,West Covina,CA,91792,34.02,-117.89,$22681,$33483,$196,698,5
3,Everlee Clark,63,63,1957,1,Female,3 Madison Street,NaN,New York,NY,10069,40.71,-73.99,$163145,$249925,$202328,722,4
4,Kyle Peterson,43,70,1976,9,Male,9620 Valley Stream Drive,NaN,San Francisco,CA,94117,37.76,-122.44,$53797,$109687,$183855,675,1

In [6]:
cards.head()

,User,CARD INDEX,Card Brand,Card Type,Card Number,Expires,CVV,Has Chip,Cards Issued,Credit Limit,Acct Open Date,Year PIN last Changed,Card on Dark Web
0,0,0,Visa,Debit,4344676511950444,12/2022,623,YES,2,$24295,09/2002,2008,No
1,0,1,Visa,Debit,4956965974959986,12/2020,393,YES,2,$21968,04/2014,2014,No
2,0,2,Visa,Debit,4582313478255491,02/2024,719,YES,2,$46414,07/2003,2004,No
3,0,3,Visa,Credit,4879494103069057,08/2024,693,NO,1,$12400,01/2003,2012,No
4,0,4,Mastercard,Debit (Prepaid),5722874738736011,03/2009,75,YES,1,$28,09/2008,2009,No

In [7]:
transactions.head()

,User,Card,Year,Month,Day,Time,Amount,Use Chip,Merchant Name,Merchant City,Merchant State,Zip,MCC,Errors?,Is Fraud?
0,0,0,2002,9,1,06:21,$134.09,Swipe Transaction,3527213246127876953,La Verne,CA,91750.0,5300,NaN,No
1,0,0,2002,9,1,06:42,$38.48,Swipe Transaction,-727612092139916043,Monterey Park,CA,91754.0,5411,NaN,No
2,0,0,2002,9,2,06:22,$120.34,Swipe Transaction,-727612092139916043,Monterey Park,CA,91754.0,5411,NaN,No
3,0,0,2002,9,2,17:45,$128.95,Swipe Transaction,3414527459579106770,Monterey Park,CA,91754.0,5651,NaN,No
4,0,0,2002,9,3,06:23,$104.71,Swipe Transaction,5817218446178736267,La Verne,CA,91750.0,5912,NaN,No

In [8]:
# understanding data structure
users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 18 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Person                       2000 non-null   object
 1   Current Age                  2000 non-null   int64
 2   Retirement Age               2000 non-null   int64
 3   Birth Year                   2000 non-null   int64
 4   Birth Month                  2000 non-null   int64
 5   Gender                       2000 non-null   object
 6   Address                      2000 non-null   object
 7   Apartment                    528 non-null    float64
 8   City                         2000 non-null   object
 9   State                        2000 non-null   object
 10  Zipcode                      2000 non-null   int64
 11  Latitude                     2000 non-null   float64
 12  Longitude                    2000 non-null   float64
 13  Per Capita Income - Zipcode  2000 non-null   object
 14  Yearly Income - Person       2000 non-null   object
 15  Total Debt                   2000 non-null   object
 16  FICO Score                   2000 non-null   int64
 17  Num Credit Cards             2000 non-null   int64
dtypes: float64(3), int64(7), object(8)
memory usage: 281.4+ KB

In [9]:
cards.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6146 entries, 0 to 6145
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   User                   6146 non-null   int64
 1   CARD INDEX             6146 non-null   int64
 2   Card Brand             6146 non-null   object
 3   Card Type              6146 non-null   object
 4   Card Number            6146 non-null   int64
 5   Expires                6146 non-null   object
 6   CVV                    6146 non-null   int64
 7   Has Chip               6146 non-null   object
 8   Cards Issued           6146 non-null   int64
 9   Credit Limit           6146 non-null   object
 10  Acct Open Date         6146 non-null   object
 11  Year PIN last Changed  6146 non-null   int64
 12  Card on Dark Web       6146 non-null   object
dtypes: int64(6), object(7)
memory usage: 624.3+ KB

In [10]:
transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24386900 entries, 0 to 24386899
Data columns (total 15 columns):
 #   Column          Dtype
---  ------          -----
 0   User            int64
 1   Card            int64
 2   Year            int64
 3   Month           int64
 4   Day             int64
 5   Time            object
 6   Amount          object
 7   Use Chip        object
 8   Merchant Name   int64
 9   Merchant City   object
 10  Merchant State  object
 11  Zip             float64
 12  MCC             int64
 13  Errors?         object
 14  Is Fraud?       object
dtypes: float64(1), int64(7), object(7)
memory usage: 2.7+ GB

In [11]:
# Statistical Summary
users.describe(include='all')

,Person,Current Age,Retirement Age,Birth Year,Birth Month,Gender,Address,Apartment,City,State,Zipcode,Latitude,Longitude,Per Capita Income - Zipcode,Yearly Income - Person,Total Debt,FICO Score,Num Credit Cards
count,2000,2000.000000,2000.000000,2000.000000,2000.000000,2000,2000,528.000000,2000,2000,2000.000000,2000.000000,2000.000000,2000,2000,2000,2000.000000,2000.000000
unique,1993,NaN,NaN,NaN,NaN,2,1999,NaN,1286,51,NaN,NaN,NaN,1754,1948,1880,NaN,NaN
top,Magdalena Farhad,NaN,NaN,NaN,NaN,Female,506 Washington Lane,NaN,Houston,CA,NaN,NaN,NaN,$0,$44128,$0,NaN,NaN
freq,2,NaN,NaN,NaN,NaN,1016,2,NaN,22,244,NaN,NaN,NaN,15,3,102,NaN,NaN
mean,NaN,45.391500,66.237500,1973.803000,6.439000,NaN,NaN,693.547348,NaN,NaN,50535.412000,37.389225,-91.554765,NaN,NaN,NaN,709.734500,3.073000
std,NaN,18.414092,3.628867,18.421234,3.565338,NaN,NaN,1897.157861,NaN,NaN,29359.754742,5.114324,16.283293,NaN,NaN,NaN,67.221949,1.637379
min,NaN,18.000000,50.000000,1918.000000,1.000000,NaN,NaN,1.000000,NaN,NaN,1060.000000,20.880000,-159.410000,NaN,NaN,NaN,480.000000,1.000000
25%,NaN,30.000000,65.000000,1961.000000,3.000000,NaN,NaN,5.000000,NaN,NaN,28214.250000,33.837500,-97.395000,NaN,NaN,NaN,681.000000,2.000000
50%,NaN,44.000000,66.000000,1975.000000,7.000000,NaN,NaN,10.000000,NaN,NaN,46305.500000,38.250000,-86.440000,NaN,NaN,NaN,711.500000,3.000000
75%,NaN,58.000000,68.000000,1989.000000,10.000000,NaN,NaN,95.250000,NaN,NaN,77086.250000,41.200000,-80.130000,NaN,NaN,NaN,753.000000,4.000000
max,NaN,101.000000,79.000000,2002.000000,12.000000,NaN,NaN,9940.000000,NaN,NaN,99508.000000,61.200000,-68.670000,NaN,NaN,NaN,850.000000,9.000000

In [12]:
cards.describe(include='all')

,User,CARD INDEX,Card Brand,Card Type,Card Number,Expires,CVV,Has Chip,Cards Issued,Credit Limit,Acct Open Date,Year PIN last Changed,Card on Dark Web
count,6146.000000,6146.000000,6146,6146,6.146000e+03,6146,6146.000000,6146,6146.000000,6146,6146,6146.000000,6146
unique,NaN,NaN,4,3,NaN,259,NaN,2,NaN,3654,303,NaN,1
top,NaN,NaN,Mastercard,Debit,NaN,02/2020,NaN,YES,NaN,$0,02/2020,NaN,No
freq,NaN,NaN,3209,3511,NaN,377,NaN,5500,NaN,31,607,NaN,6146
mean,1003.477058,1.472502,NaN,NaN,4.820426e+15,NaN,506.220794,NaN,1.503091,NaN,NaN,2013.436707,NaN
std,571.724745,1.463294,NaN,NaN,1.328582e+15,NaN,289.431123,NaN,0.519191,NaN,NaN,4.270699,NaN
min,0.000000,0.000000,NaN,NaN,3.001055e+14,NaN,0.000000,NaN,1.000000,NaN,NaN,2002.000000,NaN
25%,508.250000,0.000000,NaN,NaN,4.486365e+15,NaN,257.000000,NaN,1.000000,NaN,NaN,2010.000000,NaN
50%,1004.000000,1.000000,NaN,NaN,5.108957e+15,NaN,516.500000,NaN,1.000000,NaN,NaN,2013.000000,NaN
75%,1493.750000,2.000000,NaN,NaN,5.585237e+15,NaN,756.000000,NaN,2.000000,NaN,NaN,2017.000000,NaN
max,1999.000000,8.000000,NaN,NaN,6.997197e+15,NaN,999.000000,NaN,3.000000,NaN,NaN,2020.000000,NaN

In [13]:
transactions.describe(include='all')

,User,Card,Year,Month,Day,Time,Amount,Use Chip,Merchant Name,Merchant City,Merchant State,Zip,MCC,Errors?,Is Fraud?
count,2.438690e+07,2.438690e+07,2.438690e+07,2.438690e+07,2.438690e+07,24386900,24386900,24386900,2.438690e+07,24386900,21666079,2.150876e+07,2.438690e+07,388431,24386900
unique,NaN,NaN,NaN,NaN,NaN,1440,98953,3,NaN,13429,223,NaN,NaN,23,2
top,NaN,NaN,NaN,NaN,NaN,12:31,$80.00,Swipe Transaction,NaN,ONLINE,CA,NaN,NaN,Insufficient Balance,No
freq,NaN,NaN,NaN,NaN,NaN,30604,250984,15386082,NaN,2720821,2591830,NaN,NaN,242783,24357143
mean,1.001019e+03,1.351366e+00,2.011955e+03,6.525064e+00,1.571812e+01,NaN,NaN,NaN,-4.769230e+17,NaN,NaN,5.095644e+04,5.561171e+03,NaN,NaN
std,5.694612e+02,1.407154e+00,5.105921e+00,3.472355e+00,8.794073e+00,NaN,NaN,NaN,4.758940e+18,NaN,NaN,2.939707e+04,8.793154e+02,NaN,NaN
min,0.000000e+00,0.000000e+00,1.991000e+03,1.000000e+00,1.000000e+00,NaN,NaN,NaN,-9.222899e+18,NaN,NaN,5.010000e+02,1.711000e+03,NaN,NaN
25%,5.100000e+02,0.000000e+00,2.008000e+03,3.000000e+00,8.000000e+00,NaN,NaN,NaN,-4.500543e+18,NaN,NaN,2.837400e+04,5.300000e+03,NaN,NaN
50%,1.006000e+03,1.000000e+00,2.013000e+03,7.000000e+00,1.600000e+01,NaN,NaN,NaN,-7.946765e+17,NaN,NaN,4.674200e+04,5.499000e+03,NaN,NaN
75%,1.477000e+03,2.000000e+00,2.016000e+03,1.000000e+01,2.300000e+01,NaN,NaN,NaN,3.189517e+18,NaN,NaN,7.756400e+04,5.812000e+03,NaN,NaN
max,1.999000e+03,8.000000e+00,2.020000e+03,1.200000e+01,3.100000e+01,NaN,NaN,NaN,9.223292e+18,NaN,NaN,9.992800e+04,9.402000e+03,NaN,NaN

In [14]:
# checking missing values
users.isnull().sum()

Person                            0
Current Age                       0
Retirement Age                    0
Birth Year                        0
Birth Month                       0
Gender                            0
Address                           0
Apartment                      1472
City                              0
State                             0
Zipcode                           0
Latitude                          0
Longitude                         0
Per Capita Income - Zipcode       0
Yearly Income - Person            0
Total Debt                        0
FICO Score                        0
Num Credit Cards                  0
dtype: int64

In [15]:
cards.isnull().sum()

User                     0
CARD INDEX               0
Card Brand               0
Card Type                0
Card Number              0
Expires                  0
CVV                      0
Has Chip                 0
Cards Issued             0
Credit Limit             0
Acct Open Date           0
Year PIN last Changed    0
Card on Dark Web         0
dtype: int64

In [16]:
transactions.isnull().sum()

User                     0
Card                     0
Year                     0
Month                    0
Day                      0
Time                     0
Amount                   0
Use Chip                 0
Merchant Name            0
Merchant City            0
Merchant State     2720821
Zip                2878135
MCC                      0
Errors?           23998469
Is Fraud?                0
dtype: int64

In [17]:
# checking duplicate rows
users.duplicated().sum()

np.int64(0)

In [18]:
cards.duplicated().sum()

np.int64(0)

In [19]:
transactions.duplicated().sum()

np.int64(66)

In [20]:
# count unique value
users.nunique()

Person                         1993
Current Age                      80
Retirement Age                   29
Birth Year                       80
Birth Month                      12
Gender                            2
Address                        1999
Apartment                       199
City                           1286
State                            51
Zipcode                        1815
Latitude                        989
Longitude                      1224
Per Capita Income - Zipcode    1754
Yearly Income - Person         1948
Total Debt                     1880
FICO Score                      321
Num Credit Cards                  9
dtype: int64

In [21]:
cards.nunique()

User                     2000
CARD INDEX                  9
Card Brand                  4
Card Type                   3
Card Number              6146
Expires                   259
CVV                       998
Has Chip                    2
Cards Issued                3
Credit Limit             3654
Acct Open Date            303
Year PIN last Changed      19
Card on Dark Web            1
dtype: int64

In [22]:
transactions.nunique()

User                2000
Card                   9
Year                  30
Month                 12
Day                   31
Time                1440
Amount             98953
Use Chip               3
Merchant Name     100343
Merchant City      13429
Merchant State       223
Zip                27321
MCC                  109
Errors?               23
Is Fraud?              2
dtype: int64

In [23]:
# Examine Key Columns
users["Gender"].value_counts()

Gender
Female    1016
Male       984
Name: count, dtype: int64

In [24]:
cards["Card Brand"].value_counts()

Card Brand
Mastercard    3209
Visa          2326
Amex           402
Discover       209
Name: count, dtype: int64

In [25]:
cards["Card Type"].value_counts()

Card Type
Debit              3511
Credit             2057
Debit (Prepaid)     578
Name: count, dtype: int64

In [26]:
transactions["Use Chip"].value_counts()

Use Chip
Swipe Transaction     15386082
Chip Transaction       6287598
Online Transaction     2713220
Name: count, dtype: int64

In [27]:
transactions["Is Fraud?"].value_counts()

Is Fraud?
No     24357143
Yes       29757
Name: count, dtype: int64