In [2]:
import pandas as pd
import numpy as np

In [4]:
# importing datasets
users = pd.read_csv("../Dataset/Raw_Data/users.csv")
cards = pd.read_csv("../Dataset/Raw_Data/cards.csv")
transactions = pd.read_csv("../Dataset/Raw_Data/credit_card_transactions.csv")

In [5]:
# checking currency column (users, cards, transaction)
users[['Per Capita Income - Zipcode',
       'Yearly Income - Person',
       'Total Debt']].head()

  Per Capita Income - Zipcode Yearly Income - Person Total Debt
0                      $29278                 $59696    $127613
1                      $37891                 $77254    $191349
2                      $22681                 $33483       $196
3                     $163145                $249925    $202328
4                      $53797                $109687    $183855

In [9]:
cards['Credit Limit'].head()

0    $24295
1    $21968
2    $46414
3    $12400
4       $28
Name: Credit Limit, dtype: object

In [7]:
transactions['Amount'].head()

0    $134.09
1     $38.48
2    $120.34
3    $128.95
4    $104.71
Name: Amount, dtype: object

In [28]:
# convert currency column from objects to float64 (We'll remove $ and commas)
# users
currency_columns = [
    'Per Capita Income - Zipcode',
    'Yearly Income - Person',
    'Total Debt'
]

for col in currency_columns:
    if users[col].dtype == 'object':
        users[col] = (
            users[col]
            .str.replace('$', '', regex=False)
            .str.replace(',', '', regex=False)
            .astype(float)
        )

In [30]:
# cards
if cards['Credit Limit'].dtype == 'object':
    cards['Credit Limit'] = (
        cards['Credit Limit']
        .str.replace('$', '', regex=False)
        .str.replace(',', '', regex=False)
        .astype(float)
    )

In [31]:
if transactions['Amount'].dtype == 'object':
    transactions['Amount'] = (
        transactions['Amount']
        .str.replace('$', '', regex=False)
        .str.replace(',', '', regex=False)
        .astype(float)
    )

In [32]:
users.info()
cards.info()
transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 18 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Person                       2000 non-null   object
 1   Current Age                  2000 non-null   int64
 2   Retirement Age               2000 non-null   int64
 3   Birth Year                   2000 non-null   int64
 4   Birth Month                  2000 non-null   int64
 5   Gender                       2000 non-null   object
 6   Address                      2000 non-null   object
 7   Apartment                    528 non-null    float64
 8   City                         2000 non-null   object
 9   State                        2000 non-null   object
 10  Zipcode                      2000 non-null   int64
 11  Latitude                     2000 non-null   float64
 12  Longitude                    2000 non-null   float64
 13  Per Capita Income - Zipcode  2000 non-null   float64
 14  Yearly Income - Person       2000 non-null   float64
 15  Total Debt                   2000 non-null   float64
 16  FICO Score                   2000 non-null   int64
 17  Num Credit Cards             2000 non-null   int64
dtypes: float64(6), int64(7), object(5)
memory usage: 281.4+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6146 entries, 0 to 6145
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   User                   6146 non-null   int64
 1   CARD INDEX             6146 non-null   int64
 2   Card Brand             6146 non-null   object
 3   Card Type              6146 non-null   object
 4   Card Number            6146 non-null   int64
 5   Expires                6146 non-null   object
 6   CVV                    6146 non-null   int64
 7   Has Chip               6146 non-null   object
 8   Cards Issued           6146 non-null   int64
 9   Credit Limit           6146 non-null   float64
 10  Acct Open Date         6146 non-null   object
 11  Year PIN last Changed  6146 non-null   int64
 12  Card on Dark Web       6146 non-null   object
dtypes: float64(1), int64(6), object(6)
memory usage: 624.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24386900 entries, 0 to 24386899
Data columns (total 15 columns):
 #   Column          Dtype
---  ------          -----
 0   User            int64
 1   Card            int64
 2   Year            int64
 3   Month           int64
 4   Day             int64
 5   Time            object
 6   Amount          float64
 7   Use Chip        object
 8   Merchant Name   int64
 9   Merchant City   object
 10  Merchant State  object
 11  Zip             float64
 12  MCC             int64
 13  Errors?         object
 14  Is Fraud?       object
dtypes: float64(2), int64(7), object(6)
memory usage: 2.7+ GB

In [22]:
# handling Missing Values
users['Apartment'].value_counts(dropna=False)

Apartment
NaN       1472
2.0         32
1.0         31
6.0         30
8.0         29
          ...
12.0         1
6486.0       1
9906.0       1
768.0        1
955.0        1
Name: count, Length: 200, dtype: int64

In [23]:
transactions['Merchant State'].value_counts(dropna=False)

Merchant State
NaN                                 2720821
CA                                  2591830
TX                                  1793298
FL                                  1458699
NY                                  1446864
                                     ...
Togo                                      2
Democratic Republic of the Congo          2
Kiribati                                  1
Botswana                                  1
Paraguay                                  1
Name: count, Length: 224, dtype: int64

In [24]:
transactions['Zip'].value_counts(dropna=False)

Zip
NaN        2878135
98516.0      55679
43830.0      48815
55024.0      44571
95076.0      43656
            ...
71069.0          1
56447.0          1
57456.0          1
84782.0          1
56556.0          1
Name: count, Length: 27322, dtype: int64

In [25]:
transactions['Errors?'].value_counts(dropna=False)

Errors?
NaN                                                    23998469
Insufficient Balance                                     242783
Bad PIN                                                   58918
Technical Glitch                                          48157
Bad Card Number                                           13321
Bad CVV                                                   10740
Bad Expiration                                            10716
Bad Zipcode                                                2079
Bad PIN,Insufficient Balance                                581
Insufficient Balance,Technical Glitch                       457
Bad PIN,Technical Glitch                                    128
Bad Card Number,Insufficient Balance                        122
Bad CVV,Insufficient Balance                                 89
Bad Expiration,Insufficient Balance                          78
Bad Card Number,Bad CVV                                      60
Bad Card Number,Bad Expiration                               54
Bad Expiration,Bad CVV                                       47
Bad Expiration,Technical Glitch                              32
Bad Card Number,Technical Glitch                             25
Bad CVV,Technical Glitch                                     21
Bad Zipcode,Insufficient Balance                             13
Bad Zipcode,Technical Glitch                                  7
Bad Card Number,Bad Expiration,Insufficient Balance           2
Bad Card Number,Bad Expiration,Technical Glitch               1
Name: count, dtype: int64

In [33]:
# checking Duplicate Transactions
duplicates = transactions[transactions.duplicated(keep=False)]
duplicates.head(10)

,User,Card,Year,Month,Day,Time,Amount,Use Chip,Merchant Name,Merchant City,Merchant State,Zip,MCC,Errors?,Is Fraud?
193877,13,0,2015,4,28,06:36,100.0,Chip Transaction,-4282466774399734331,Boyne City,MI,49712.0,4829,Insufficient Balance,No
193878,13,0,2015,4,28,06:36,100.0,Chip Transaction,-4282466774399734331,Boyne City,MI,49712.0,4829,Insufficient Balance,No
195220,13,1,2006,7,19,07:34,100.0,Swipe Transaction,-4282466774399734331,Boyne City,MI,49712.0,4829,Insufficient Balance,No
195221,13,1,2006,7,19,07:34,100.0,Swipe Transaction,-4282466774399734331,Boyne City,MI,49712.0,4829,Insufficient Balance,No
195329,13,1,2006,10,15,07:11,100.0,Swipe Transaction,-4282466774399734331,Boyne City,MI,49712.0,4829,Insufficient Balance,No
195330,13,1,2006,10,15,07:11,100.0,Swipe Transaction,-4282466774399734331,Boyne City,MI,49712.0,4829,Insufficient Balance,No
244171,17,2,2011,12,12,16:26,120.0,Swipe Transaction,-4282466774399734331,Prescott Valley,AZ,86314.0,4829,Insufficient Balance,No
244172,17,2,2011,12,12,16:26,120.0,Swipe Transaction,-4282466774399734331,Prescott Valley,AZ,86314.0,4829,Insufficient Balance,No
1360768,109,2,1999,12,9,04:16,120.0,Swipe Transaction,-4282466774399734331,Hammond,IN,46323.0,4829,Insufficient Balance,No
1360769,109,2,1999,12,9,04:16,120.0,Swipe Transaction,-4282466774399734331,Hammond,IN,46323.0,4829,Insufficient Balance,No

In [34]:
# removing duplicates
transactions = transactions.drop_duplicates()

(24386834, 15)

In [35]:
transactions.duplicated().sum()

np.int64(0)

In [36]:
# saving cleaned data
users.to_csv(
    "../Dataset/Cleaned_Data/users_clean.csv",
    index=False
)

cards.to_csv(
    "../Dataset/Cleaned_Data/cards_clean.csv",
    index=False
)

transactions.to_csv(
    "../Dataset/Cleaned_Data/transactions_clean.csv",
    index=False
)